name = "ito-voice"
main = "worker.js"
compatibility_date = "2024-01-01"

# CORS許可オリジン（公開用）※実際はworker.js内のallowedListで動的判定
[vars]
ALLOWED_ORIGIN = "https://all-ito-city.com"

# KVバインディング
[[kv_namespaces]]
binding = "POSTS_KV"
id = "d6cc6a0288fc41dcb764d4c5015c12b6"

[[kv_namespaces]]
binding = "PAGEVIEW_KV"
id = "8bd9161046f04164b25418668012f805"
